name: MLOps Pipeline CI

# Trigger this script automatically every time code is pushed to your main branch
on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest # Rent an isolated Linux machine on GitHub's cloud for free

    steps:
    - name: Check out your repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install required dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn evidently

    - name: Execute Automated Data Drift Check
      run: |
        python monitor_drift.py

